# Generated by Django 4.2 on 2023-04-21 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_image_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='image',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
