# Generated by Django 4.2 on 2023-04-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_profile_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='user.png', upload_to='project/profile_images'),
        ),
    ]
