# Generated by Django 4.2 on 2023-04-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='author',
            name='paswword2',
        ),
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, default='new user', max_length=500),
        ),
    ]
