# Generated by Django 4.2 on 2023-04-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_author_email_remove_author_password1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, default='project/avatars/default.png', null=True, upload_to='project/avatars'),
        ),
    ]
